import { Category, ColorPreset } from '../types/category.types';

export const CATEGORIES_STORAGE_KEY = 'expense_tracker_categories_list';

/**
 * Default standard system categories required by Expense Tracker
 */
export const DEFAULT_SYSTEM_CATEGORIES: Category[] = [
  {
    id: 'cat_food',
    name: 'Food',
    icon: 'silverware-fork-knife',
    color: '#EA580C',
    backgroundColor: '#FFF7ED',
    isActive: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_transport',
    name: 'Transport',
    icon: 'car-outline',
    color: '#0284C7',
    backgroundColor: '#F0F9FF',
    isActive: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_shopping',
    name: 'Shopping',
    icon: 'shopping-outline',
    color: '#DB2777',
    backgroundColor: '#FDF2F8',
    isActive: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_rent',
    name: 'Rent',
    icon: 'home-city-outline',
    color: '#4F46E5',
    backgroundColor: '#EEF2FF',
    isActive: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_bills',
    name: 'Bills',
    icon: 'receipt-text-outline',
    color: '#D97706',
    backgroundColor: '#FFFBEB',
    isActive: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_health',
    name: 'Health',
    icon: 'heart-pulse',
    color: '#059669',
    backgroundColor: '#ECFDF5',
    isActive: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_education',
    name: 'Education',
    icon: 'school-outline',
    color: '#7C3AED',
    backgroundColor: '#F5F3FF',
    isActive: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_entertainment',
    name: 'Entertainment',
    icon: 'movie-outline',
    color: '#9333EA',
    backgroundColor: '#FAF5FF',
    isActive: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_travel',
    name: 'Travel',
    icon: 'airplane',
    color: '#0891B2',
    backgroundColor: '#ECFEFF',
    isActive: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_groceries',
    name: 'Groceries',
    icon: 'cart-outline',
    color: '#16A34A',
    backgroundColor: '#F0FDF4',
    isActive: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_other',
    name: 'Other',
    icon: 'dots-horizontal-circle-outline',
    color: '#64748B',
    backgroundColor: '#F8FAFC',
    isActive: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

/**
 * Curated list of high-quality icons available for selection in category editor
 */
export const AVAILABLE_CATEGORY_ICONS: { name: string; label: string }[] = [
  { name: 'silverware-fork-knife', label: 'Dining' },
  { name: 'coffee', label: 'Coffee' },
  { name: 'cart-outline', label: 'Groceries' },
  { name: 'shopping-outline', label: 'Shopping' },
  { name: 'tshirt-crew-outline', label: 'Clothing' },
  { name: 'car-outline', label: 'Vehicle' },
  { name: 'gas-station', label: 'Fuel' },
  { name: 'bus', label: 'Transit' },
  { name: 'airplane', label: 'Travel' },
  { name: 'home-city-outline', label: 'Housing' },
  { name: 'receipt-text-outline', label: 'Bills' },
  { name: 'lightning-bolt-outline', label: 'Utility' },
  { name: 'wifi', label: 'Internet' },
  { name: 'phone-outline', label: 'Mobile' },
  { name: 'heart-pulse', label: 'Health' },
  { name: 'pill', label: 'Medicine' },
  { name: 'dumbbell', label: 'Fitness' },
  { name: 'school-outline', label: 'Education' },
  { name: 'book-open-page-variant-outline', label: 'Books' },
  { name: 'movie-outline', label: 'Movies' },
  { name: 'gamepad-variant-outline', label: 'Gaming' },
  { name: 'music', label: 'Music' },
  { name: 'paw', label: 'Pets' },
  { name: 'gift-outline', label: 'Gifts' },
  { name: 'wallet-outline', label: 'Wallet' },
  { name: 'chart-line', label: 'Invest' },
  { name: 'briefcase-outline', label: 'Work' },
  { name: 'tools', label: 'Maintenance' },
  { name: 'dots-horizontal-circle-outline', label: 'General' },
];

/**
 * Curated color swatches with matching accessible pastel backgrounds
 */
export const AVAILABLE_COLOR_PRESETS: ColorPreset[] = [
  { id: 'orange', name: 'Warm Orange', color: '#EA580C', backgroundColor: '#FFF7ED' },
  { id: 'amber', name: 'Golden Amber', color: '#D97706', backgroundColor: '#FFFBEB' },
  { id: 'green', name: 'Forest Green', color: '#16A34A', backgroundColor: '#F0FDF4' },
  { id: 'emerald', name: 'Fresh Emerald', color: '#059669', backgroundColor: '#ECFDF5' },
  { id: 'teal', name: 'Teal Lagoon', color: '#0D9488', backgroundColor: '#F0FDFA' },
  { id: 'cyan', name: 'Sky Cyan', color: '#0891B2', backgroundColor: '#ECFEFF' },
  { id: 'sky', name: 'Ocean Sky', color: '#0284C7', backgroundColor: '#F0F9FF' },
  { id: 'blue', name: 'Vibrant Blue', color: '#2563EB', backgroundColor: '#EFF6FF' },
  { id: 'indigo', name: 'Deep Indigo', color: '#4F46E5', backgroundColor: '#EEF2FF' },
  { id: 'violet', name: 'Royal Violet', color: '#7C3AED', backgroundColor: '#F5F3FF' },
  { id: 'purple', name: 'Bright Purple', color: '#9333EA', backgroundColor: '#FAF5FF' },
  { id: 'fuchsia', name: 'Vivid Fuchsia', color: '#C026D3', backgroundColor: '#FDF4FF' },
  { id: 'pink', name: 'Rose Pink', color: '#DB2777', backgroundColor: '#FDF2F8' },
  { id: 'rose', name: 'Crimson Rose', color: '#E11D48', backgroundColor: '#FFF1F2' },
  { id: 'slate', name: 'Classic Slate', color: '#64748B', backgroundColor: '#F8FAFC' },
];
